### ISSUE TITLE
Errors when Units are Deleted in-game

### ISSUE THREAD

**Issue by Xirema** [DeamonHunter/AWBW-Replay-Player#106]
Watching a replay where my opponent deleted a large number of units before resigning, the replay viewer spammed a bunch of errors in response.

![image](https://user-images.githubusercontent.com/1447761/193344564-80a2c2d0-7c5b-4c10-aa35-ea9b4e2a594f.png)

The following was copied from the player: 

System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at AWBWApp.Game.API.Replay.Actions.DeleteUnitAction.PerformAction(ReplayController controller)+MoveNext()
   at AWBWApp.Game.Game.Logic.ReplayController.Update()

**Comment by DeamonHunter** [comment]
Thanks for the report. Do you have the replay that caused this?

**Comment by Xirema** [comment]
It would be this game, which you can still pull the replay from: https://awbw.amarriner.com/2030.php?games_id=714530

**Comment by DeamonHunter** [comment]
Thanks. Will look into it.

Leaving this here for when I work on this: 
[714530.zip](https://github.com/DeamonHunter/AWBW-Replay-Player/files/9689222/714530.zip)
