### ISSUE TITLE
Add Option to Hide Sonja unit HP

### ISSUE THREAD

**Issue by Xirema** [DeamonHunter/AWBW-Replay-Player#124]
It can be useful, when reviewing a replay, to see things the way that the player would have seen them in-game, and in matches that involve Sonja, her units have hidden HP.

Ideally, this would be an option that has several modes:

- Off (Sonja's units always show their real HP value)
- Player (HP is shown when replaying Sonja's turn, but not when it isn't her turn)
- Fog Player (looks at the existing Fog option and shows HP values only if showing Sonja's fog perspective, and otherwise hides values if not showing her perspective)
- On (HP values are always hidden)

**Comment by DeamonHunter** [comment]
Thanks for the feedback. Will look into getting this working. Will likely have the following options

- Always
- Vision (When Vision is set to Sonja or her team.)
- Off

Not sure on making a distinction between Sonja's turn versus her vision. So atm won't work on that.

**Comment by DeamonHunter** [comment]
![AWBW_Replay_Player_iWEIAcGuVO](https://user-images.githubusercontent.com/7556376/207218550-9228a971-2246-4db0-84d2-fd4a7627e573.png)
Will be added in the next update.
