### ISSUE TITLE
Give better Error Message when attempting to download Replay for in-progress game

### ISSUE THREAD

**Issue by Xirema** [DeamonHunter/AWBW-Replay-Player#125]
![image](https://user-images.githubusercontent.com/1447761/206800173-1920f801-70b4-4b5f-80d7-6fa184666cab.png)

As shown in the image, the error message that gets generated when a user attempts to download a replay of an in-progress game is unspecific. It would be better if there were specific handling for the case of an in-progress game and a specific error message "You cannot download Replays of games that have not yet ended" or something to that effect.
```
System.Exception: Unable to find the replay of game '779749'. Does the replay still exist on AWBW?
   at AWBWApp.Game.UI.Interrupts.GetNewReplayInterrupt.attemptDownload()
```

**Comment by DeamonHunter** [comment]
Thanks for the feedback. The errors have been expanded to include the following:
- No response from AWBW. (Internet down or AWBW down)
- Game not found.
- Game not finished.
- Game too old

This should be in the next update.

![image](https://user-images.githubusercontent.com/7556376/206973053-f69f140c-2e3b-4c65-b0f3-bb9ac0d66324.png)
