### ISSUE TITLE
Next Action Not working

### ISSUE THREAD

**Issue by scott95641** [DeamonHunter/AWBW-Replay-Player#128]
When viewing a replay, the player will only advance by full turns the button for next action when hovered over say next turn while the next turn key says nothing and using a key binding doesnt work will still only advance by full turn by pressing K. I cannot see each action.

**Comment by DeamonHunter** [comment]
Hi, do you have a replay for this? If so, could you upload the replay that you noticed this with.

It might be that the replay just doesn't have any data about actions in it.

**Comment by DeamonHunter** [comment]
Going to close this. This is likely a replay specific bug that hasn't since been reported.
