### ISSUE TITLE
Unable to Import Replays from the AWBW site

### ISSUE THREAD

**Issue by Xirema** [DeamonHunter/AWBW-Replay-Player#138]
The AWBW site changed the URL that games can be viewed from, and as a result, trying to use the new URLs in the replay viewer causes the application to throw an error.

The new URL takes the form of `https://awbw.amarriner.com/game.php?games_id=######`

The error being produced when this URL is passed to the replay viewer:
![image](https://github.com/DeamonHunter/AWBW-Replay-Player/assets/1447761/b3c75d1b-8492-4c31-bbfd-b5d9b2fbc248)

The website still (for now) supports accessing games with the old `2030.php` resource, so using that form, or just passing the game ID alone seems to work okay.

**Comment by DeamonHunter** [comment]
Thanks for the heads up! Will be making an update with 61b1aa8511a0756f2ec921d9e614ab38c7ea8365 tomorrow.
