### ISSUE TITLE
`BaseDefence` field missing in three buildings in the `Buildings.json` file

### ISSUE THREAD

**Issue by y-haidar** [DeamonHunter/AWBW-Replay-Player#145]
I noticed that these three buildings do not have `BaseDefence` field in the `Buildings.json` [file](https://github.com/DeamonHunter/AWBW-Replay-Player/blob/master/AWBWApp.Resources/Json/Buildings.json). Not sure if this will cause any issues, just wanted to let you know.

WhiteNovaAirport
AzureAsteroidAirport
NoirEclipseAirport

**Comment by DeamonHunter** [comment]
Good catch. Thankfully this would only be a visual bug I believe. (Hovering over the tile will show 0 defense.)

I'll try to work a fix into a release soonish.

**Comment by DeamonHunter** [comment]
Fixed in 61b28263414617df9d51b0156da4f2357816fee4.
Update should be out tomorrow.
