### ISSUE TITLE
Missing Map

### ISSUE THREAD

**Issue by NexusQuile** [DeamonHunter/AWBW-Replay-Player#63]
Imported a couple of replays from AWBW but list of replays is showing "MISSING MAP". 
However map name is shown on the detail.
![image](https://user-images.githubusercontent.com/104992166/166930894-7eb9398c-784b-4b95-a2c0-e2af74f76268.png)

**Comment by DeamonHunter** [comment]
Thanks for the bug report. 

I keep forgetting to fix this one. Its caused by the fact that the map is downloaded after the replay is parsed. So the replay select creates a listing for it, but knows nothing about the map.

The fix is to cause an update to the listing after the map is downloaded.
