### ISSUE TITLE
Key rebinding not persistant

### ISSUE THREAD

**Issue by NexusQuile** [DeamonHunter/AWBW-Replay-Player#68]
My custom key bindings are being lost when I close and reopen the software.

I also keep expecting there to be a confirm/accept button which would close the rebind menu. I keep nearly hitting the reset button.

**Comment by DeamonHunter** [comment]
Thanks for bringing this up. The keybindings should be fixed up in the next update. 

Will look into the design to make it a bit more obvious how to close.

**Comment by DeamonHunter** [comment]
Both issues should now be fixed.
